### ISSUE TITLE
навішування кількох класів

### ISSUE THREAD

**Issue by pecourses** [IrynaKr1/fullscreen-landing#3]
https://github.com/IrynaKr1/fullscreen-landing/blob/6a3ecf6739f44c306d31b01f83eab0308321c816/index.html#L27
- селектори id прийнято не використовувати в розробці, оскільки це ставить нас в вулькі рамки: один і той самий id можна використовувати не більше одного разу на сторінку. Класично використовують селектори класів, вони створюють найменше проблем при підтримці. Щоб тут обійтися без селекторів id, можна навісити кілька класів на елемент. Для цього класи мають бути перераховано через пробіл одне від одного:
```html
 <p class="paragraph3 middle">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem nesciunt quo perferendis adipisci distinctio nemo in officia quis, harum dolor?</p>
``` 
```css
.paragraph3 {
    display: inline-block;
    font-size: 17px;
    width: calc(100% / 3);
    background: #f4f4f4;
}

.middle {
    background: #926239;
    color: #fff;
}
``` 
При цьому класи для .middle мають бути прописані нижче, ніж для .paragraph3, щоб вони були пріоритетнішими.

Також може бути інший підхід, коли на різні елементи буде навішено різні класи:
```html
      <p class="paragraph4" >Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem nesciunt quo perferendis adipisci distinctio nemo in officia quis, harum dolor?</p>
      <p class="paragraph3" >Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem nesciunt quo perferendis adipisci distinctio nemo in officia quis, harum dolor?</p>
      <p class="paragraph4" >Lorem ipsum dolor sit amet consectetur, adipisicing elit. Exercitationem nesciunt quo perferendis adipisci distinctio nemo in officia quis, harum dolor?</p>
``` 
```css
.paragraph3,
.paragraph4 {
  display: inline-block;
  font-size: 17px;
  width: calc(100% / 3);
}

.paragraph3 {
  background: #f4f4f4;
}

.paragraph4 {
  background: #926239;
  color: #fff;
}
```
